### ISSUE TITLE
Is this accepting pull requests?

### ISSUE THREAD

**Issue by LilSpazJoekp** [Lanjelin/AmiiboConverter#1]
I would like do so refactoring and improvements and was wondering if this was still maintained.

**Comment by Lanjelin** [comment]
Still keeping an eye on the project, yes.  
My intention is to keep it in working order at least.

**Comment by LilSpazJoekp** [comment]
Good to hear! I have a bunch of improvements I want to make. Would you prefer one large PR or a bunch of smaller ones? Some of the smaller ones will still be large cause it required a bunch of changes all at once.

**Comment by Lanjelin** [comment]
Whatever is more convenient and/or makes more sense I guess.
