### ISSUE TITLE
Decryption Keys?

### ISSUE THREAD

**Issue by Anonymous3-a** [Lanjelin/AmiiboConverter#2]
In this case, I want to convert an NFC from my Flipper Zero (the Lv50 Link from [my F0's custom firmware](https://github.com/RogueMaster/flipperzero-firmware-wPlugins), if that helps), but it says `WARNING:root:Missing decryption keys!`. How do I get the decryption keys?

**Comment by Lanjelin** [comment]
### [What does it require?](https://github.com/Lanjelin/AmiiboConverter#what-does-it-require)

> For anything but pure bin-to-nfc / nfc-to-bin conversion, you need the correct decryption keys in the same folder as the script, these are files commonly called unfixed-info.bin and locked-secret.bin. A merged version of these files called key_retail.bin can also be used. These files are not provided.

The files are considered as copyrighted, that's the reason they're not provided here.  
Your favorite search engine should be able to help you out though.
